name: docs

on:
  workflow_dispatch:

jobs:
  docs:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019, windows-2022, macos-11, macos-12, macos-13, ubuntu-20.04, ubuntu-22.04]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Build VuePress site
        run: yarn ghbuild
