name: docs

on:
  workflow_dispatch:

jobs:
  docs:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Build VuePress site
        run: yarn ghbuild
      - name: Deploy to GitHub Pages
        uses: actions/upload-artifact@v4
        with:
          path: docs/.vuepress/dist
